version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: sa201603191
      MYSQL_DATABASE: tp8
    ports:
      - "3306:3306"
  server:
    build: SERVER/.
    command: node app.js
    ports:
      - "80:80"
    depends_on:
      - db