version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD: sa201603191
      - MYSQL_DATABASE: tp8
      - MYSQL_USER: user
      - MYSQL_PASSWORD: sa201603191
  server:
    build: SERVER/.
    command: node app.js
    ports:
      - "80:80"
    depends_on:
      - db
    links:
      - db:db  